### ISSUE TITLE
accept props

### ISSUE THREAD

**Issue by zouhir** [zouhir/preact-habitat#1]
it's good to be able to pass props in widget configs

example: if we have a video player widget - would be great if the client\host DOM can pass props within the JSON config like what we already have in `{ "clone": "id-xyz" }` but:

```html
<script type="widget/config">
  {
    "props":{
      "videoId: "11223300",
      "playFromStart": true
    }
}
</script>
```

**Comment by rdmurphy** [comment]
Could also be cool to be able to pass them as properties on the container element (or the `<script>` tag itself), too. Would have to come up with a namespace that could be observed for that purpose, though.

**Comment by zouhir** [comment]
@rdmurphy I actually thought of data attributes. but found a JSON config to look more neat after looking at the following options:

```
<script data-props-videoId ="11223300" data-props-playFromStart="true" >
```

or 

```
<script data-props="{ ...props }" >
```

I'm open to suggestions

Namespace idea is KOOL! I love it

**Comment by luisrudge** [comment]
@zouhir can we make it possible to pass props from the render call?

**Comment by zouhir** [comment]
@luisrudge in this version, what you can do in a case where you want to render widget with extra props:

```
let extraPropsObj = {...};
let ExtraPropsApp = () => (<App ...extraPropsObj />)

let appHabitat =  habitat(ExtraPropsApp);
appHabitat.render({ ... })
```

that what works now out of the box, will consider allowing passing `habitat(<App ... />)` in future releases :)

hope my answer was helpful

**Comment by luisrudge** [comment]
That makes sense. Thanks!

**Comment by kentcdodds** [comment]
I'd totally love it if props could include functions. Could do:

```html
<script type="text/props">
  window.widgetVariable = {
    props: {
      videoId: '11223300',
      playFromStart: true,
      onPlay: function () {
        console.log('played!')
      }
    }
  }
</script>
```

Then we could delete `widgetVariable` off of `window` :+1:

My use case is with downshift, I'd love to be able to expose the full API and allow you to render whatever you'd like using whatever framework you want :smile: Need a full function to do that though...

**Comment by zouhir** [comment]
That idea is so damn awesome.

but instead of writing in inside HTML we can expose DOM events and get them to consume it whenever.

Oh! @kentcdodds would you like me to allow you expose DOM events? so you can have a global module name, I am very busy now but can deliver this by next Friday!

your users can do: `UMDModuleName.on('play', () => {...})` ?

You can do:

`habitat.registerDomEvent('play', .....)`

**Comment by kentcdodds** [comment]
Yeah, that'd be pretty legit :+1:

That'd definitely allow me to do what I want to do here! :tada:

**Comment by Rouvo** [comment]
Hello,

I also would like to pass functions to a widget. From reading this thread I assume you already did implement the exposing of DOM events? However, I cannot find anything like `registerDomEvent`

**Comment by NicHaley** [comment]
Similar to @Rouvo I also require this functionality
