### ISSUE TITLE
Props removed with Clean Option

### ISSUE THREAD

**Issue by stuartflanagan** [zouhir/preact-habitat#16]
When using options.clean in conjunction with props from a script tag the clean operation removes the props before the preact component is instantiated.

**Comment by stuartflanagan** [comment]
I will try and get a PR for this soon.

**Comment by zouhir** [comment]
Uh oh! good catch! in my applications I never mixed those so I am really sorry that happened! I am busy with my university until the 29th -- I'd appreciate a PR but if you are busy I can totally fix it for you after!

**Comment by stuartflanagan** [comment]
Happy to give it a go.

**Comment by zouhir** [comment]
I believe this issue should be fixed now! 😄 in #17 !!

**Comment by zouhir** [comment]
Fixed and I think I can safely close this!
