### ISSUE TITLE
Clean up habitat widget

### ISSUE THREAD

**Issue by fantasia949** [zouhir/preact-habitat#20]
When I want to remove a habitat widget from DOM, I expect the componentWillUnmount() will be called to release internal resources, but in actually, it does not.

How can I clean up its internal resources in this case?

**Comment by zouhir** [comment]
hmm.. Habitat will only render your <App /> but I don't know what are you doing later with your DOM.

Is it not possible to write your own in needed functionality `componentWillUnmount` of the <App /> you have sent the habitat to render?
