### ISSUE TITLE
Update doc example

### ISSUE THREAD

**Issue by ShavidzeT** [zouhir/preact-habitat#27]
```js
import habitat from 'preact-habitat';
import WidgetAwesome from './components/WidgetAwesome';

let habitat = habitat(WidgetAwesome);
```
`habitat` is already used while we import package and it would be better if we don't override variable.
I think it needs to have different name like `habitatTemplate` or something else except `habitat`

**Comment by zouhir** [comment]
just merged a fix for this example! good catch! thank you!
