### ISSUE TITLE
Compatibility with Unistore

### ISSUE THREAD

**Issue by rafaellages-hotmart** [zouhir/preact-habitat#36]
Hi guys I'm trying to use preact habitat with a widget that uses unistore https://github.com/developit/unistore 
Do you have any ideas how to use them together, as unistore require me to have a Provider wrapper:
```
  <Provider store={store}>
    <App />
  </Provider>
```
and habitat require me to pass my app as a parameter:
```
const { render } = habitat(App);
render();
```

**Comment by ascorbic** [comment]
@rafaellages-hotmart I'm assuming you have a solution now, but you could put the `<Provider>` inside the App component. e.g.

```jsx
export const App = () => (
  <Provider store={store}>
  {  //The rest of your components }
  </Provider>
)
```

**Comment by rafaellages-hotmart** [comment]
Yeah, thats what I did. Its actually very basic, I just understood it wrong.
