### ISSUE TITLE
Compatablity with Preact X

### ISSUE THREAD

**Issue by RaghulXander** [zouhir/preact-habitat#41]
`⚠ WARN BabelEsmPlugin: ../node_modules/preact-habitat/dist/preact-habitat.es.js 151:25-31`
"export 'default' (imported as 'preact') was not found in 'preact

**Comment by joaodfmota** [comment]
https://github.com/zouhir/preact-habitat/pull/38

**Comment by RaghulXander** [comment]
Still I face the same issue i have updated Preact version!!! @joaodfmota

**Comment by joaodfmota** [comment]
I'm using the master and it's working fine.
```json
"preact-habitat": "zouhir/preact-habitat#master",
```

The latest published version is 3.2.2 on 2018-07-06 and the pull request is dated 2019-04-18

**Comment by sampotts** [comment]
@zouhir Can bump the version and publish to npm?

**Comment by ascorbic** [comment]
Fixed in version 3.3.0, which should now be available in npm.
