### ISSUE TITLE
Compatibility of adding Preact-portal in preact-habitat

### ISSUE THREAD

**Issue by RaghulXander** [zouhir/preact-habitat#42]
Was trying to add preact-portal inside my habitat app but didnt works

**Comment by RaghulXander** [comment]
Does createPortal of preact/compat works in preact-habitat @joaodfmota @ascorbic

**Comment by zouhir** [comment]
I am not sure what Preact portal is, and I am very sorry for not looking into this project for so long. If this is still a need after all these years, please reopen with more details about your use case.
