### ISSUE TITLE
Add maintainers to this project

### ISSUE THREAD

**Issue by ascorbic** [zouhir/preact-habitat#44]
@zouhir You've said on your profile that you're no longer able to maintain your open source projects. Would you be able to add maintainers to this project. I'm happy to help out if you give me access to the project on Github and NPM. I'm using this quite heavily in several important projects, so I am able to devote some time to it.

**Comment by zouhir** [comment]
Hi @ascorbic thank you a ton for this, I looked at your GitHub and Blog and I believe you can be an amazing maintainer and do much better job than I did, super excited and adding your right now!

**Comment by ascorbic** [comment]
That's great, thanks. Could you add me as a collaborator on NPM too, so I can publish updates?

**Comment by zouhir** [comment]
I already did that same time I added you to GitHub, I will confirm.

**Comment by ascorbic** [comment]
Ah, I see that now. Thanks. I'm hoping to do a major version bump to coincide with the full Preact 10 release, which looks imminent, as I *think* it may be a breaking change.
